### ISSUE TITLE
Appveyor fails on Python 3.6

### ISSUE THREAD

**Issue by mgedmin** [mgedmin/check-manifest#79]
See https://ci.appveyor.com/project/mgedmin/check-manifest/build/build-78-master/job/d41lac1gwuustvon:

```
======================================================================
ERROR: test_get_vcs_files_nonascii_filenames (tests.TestBzr)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\projects\check-manifest\tests.py", line 886, in test_get_vcs_files_nonascii_filenames
    self.assertEqual(get_vcs_files(), [filename])
  File "C:\projects\check-manifest\check_manifest.py", line 455, in get_vcs_files
    return normalize_names(vcs.get_versioned_files())
  File "C:\projects\check-manifest\check_manifest.py", line 380, in get_versioned_files
    output = run(['bzr', 'ls', '-VR'], encoding=encoding)
  File "C:\projects\check-manifest\check_manifest.py", line 152, in run
    output = output.decode(encoding)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x82 in position 0: invalid start byte

```

I cannot reproduce this on Linux, or on my Windows Jenkins machine.

**Comment by mgedmin** [comment]
I suspect this bit:

```python
class Bazaar(VCS):
    metadata_name = '.bzr'

    @classmethod
    def _get_terminal_encoding(self):
        # Based on bzrlib.osutils.get_terminal_encoding()
        encoding = getattr(sys.stdout, 'encoding', None)
        if not encoding:
            encoding = getattr(sys.stdin, 'encoding', None)
        if encoding == 'cp0':  # "no codepage"
            encoding = None
        # NB: bzrlib falls back on bzrlib.osutils.get_user_encoding(),
        # which is like locale.getpreferredencoding() on steroids, and
        # also includes a fallback from 'ascii' to 'utf-8' when
        # sys.platform is 'darwin'.  This is probably something we might
        # want to do in run(), but I'll wait for somebody to complain
        # first, since I don't have a Mac OS X machine and cannot test.
        return encoding
```

is misfiring because Python 3.6 makes sys.stdout.encoding always be 'UTF-8'.  So I can't figure out what encoding `bzr ls` will give me, since `bzr` itself is still on Python 2.7.

**Comment by mgedmin** [comment]
Still no idea why I wasn't seeing this error on my Jenkins.
